FROM debian:bookworm-slim

RUN apt-get update
RUN apt-get -y install git
RUN apt-get -y install python3 python3-pip python3-venv python3-tk

#### armv7
# docker build --platform linux/arm/v7 -t python_eef:armv7 -f ./Dockerfile_arm .
# win
# docker run -v %cd%:/home/workspace -w /home/workspace -it --platform linux/arm/v7 python_eef:armv7 bash
# linux
# docker run -v $(pwd):/home/workspace -w /home/workspace -it --platform linux/arm/v7 python_eef:armv7 bash /home/workspace/Scripts/build_linux_arm.sh

#### arm64
# docker build --platform linux/arm64 -t python_arm64 -f ./Dockerfile_arm .
# docker run -it --platform linux/arm64 python_arm64 bash
# win
# docker run -v %cd%:/home/workspace -w /home/workspace -it --platform linux/arm64 python_arm64 bash
# linux
# docker run -v $(pwd):/home/workspace -w /home/workspace -it --platform linux/arm64 python_arm64 bash /home/workspace/Scripts/build_linux_arm.sh