FROM debian:bookworm-slim

RUN apt-get update
RUN apt-get -y install git
# RUN apt-get -y install binutils
# RUN apt-get -y install build-essential libssl-dev libffi-dev
# RUN apt-get -y install python3 python3-pip python3-dev python3-venv python3-tk
RUN apt-get -y install python3 python3-pip python3-venv python3-tk
# RUN apt-get -y install build-essential
# RUN apt-get -y install pkg-config
# RUN apt-get -y install libffi-dev
# RUN apt-get -y install libssl-dev
# RUN apt-get -y install curl
# RUN python3 -m pip install --upgrade pip

# RUST
# RUN curl --proto '=https' --tlsv1.3 -sSf https://sh.rustup.rs | sh -s -- -y
# set env
# . "$HOME/.cargo/env"

# python3 -m venv /home/venv

# docker build --platform linux/arm/v7 -t python_eef:armv7 -f ./Dockerfile_armv7 .
# win
# docker run -v %cd%:/home/workspace -w /home/workspace -it --platform linux/arm/v7 python_eef:armv7 bash
# linux
# docker run -v $(pwd):/home/workspace -w /home/workspace -it --platform linux/arm/v7 python_eef:armv7 bash /home/workspace/Scripts/build_linux.sh

# docker buildx build --platform linux/amd64,linux/arm64 . (not working, not support docker driver)
# docker run -p 4200:4200 -p 9876:9876 -it -v %cd%:/home/workspace angular_18 sh

# 