name: main_ci_cd

on: [push]

jobs:
  linux_arm64_executable:
          runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v4
          - name: run PyInstaller in docker
            run: |
              ls -la
              echo $(pwd)
              docker version
              docker images
              docker buildx build -t python_arm64 .
              docker images
              docker inspect python_arm64
              docker run -v $(pwd):/home/workspace -w /home/workspace python_arm64 bash /home/workspace/Scripts/build_linux.sh
          - name: Create LinuxArm64 Artefact
            uses: actions/upload-artifact@v4
            with:
              # Artifact name
              name: espeasyflasher_linux_arm64
              # A file, directory or wildcard pattern that describes what to upload
              path: ./dist
              # The desired behavior if no files are found using the provided path.
