name: main_ci_cd
#on: [push]
on:
  push:
    branches:
      - '**'

jobs:
  test:
    uses: hredan/ESPEASYFLASHER_2.0/.github/workflows/test.yml@main
  build-targets:
    needs: test
    uses: hredan/ESPEASYFLASHER_2.0/.github/workflows/build_targets.yml@34-custom-logo-does-not-shown
    with:
      target: 'macos13'