name: main_ci_cd

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python "3.10"
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyserial
        pip install esptool
        pip install pylint
    - name: Analysing code with pylint
      run: |        
        pylint --rcfile=./Scripts/pylint.rc espeasyflasher.py
        pylint --rcfile=./Scripts/pylint.rc ./eef_modules
        pylint --rcfile=./Scripts/pylint.rc ./tests
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python "3.10"
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install esptool
    - name: Testing EspEasyFlasher_2.0
      run: pytest tests
  windows_exe:
    runs-on: windows-latest
    needs: [pylint, pytest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python "3.10"
      uses: actions/setup-python@v3
      with: 
        python-version: "3.10"
    - name: run PyInstaller
      run: |
        python --version
        pip install pyinstaller
        pip install esptool
        python -m PyInstaller -F --noconsole --add-data "LogoEasyFlash.png;." --add-data "./resource/win/icon_256x256.png;." espeasyflasher.py
        copy ./ESPEasyFlasherConfig.json ./dist
        mkdir ./dist/ESP_Packages
        copy ./ESP_Packages/README.md ./dist/ESP_Packages
    - name: Create Windows Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: espeasyflasher_win
        # A file, directory or wildcard pattern that describes what to upload
        path: ./dist
        # The desired behavior if no files are found using the provided path.
  linux_x64_executable:
    runs-on: ubuntu-latest
    needs: [pylint, pytest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python "3.10"
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: run PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install esptool
        python -m PyInstaller -F --add-data "./LogoEasyFlash.png:." --name ESPEasyFlasher espeasyflasher.py
        cp ./ESPEasyFlasherConfig.json ./dist
        mkdir ./dist/ESP_Packages
        cp ./ESP_Packages/README.md ./dist/ESP_Packages
    - name: Create Linux Artefact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: espeasyflasher_linux_x64
        # A file, directory or wildcard pattern that describes what to upload
        path: ./dist
        # The desired behavior if no files are found using the provided path.
  macOs_executable:
    runs-on: macos-latest
    needs: [pylint, pytest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python "3.10"
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: run PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install esptool
        python -m PyInstaller -F --add-data "./LogoEasyFlash.png:." --icon "./resource/macOs/SleepUino.icns" --name ESPEasyFlasher espeasyflasher.py
        cp ./ESPEasyFlasherConfig.json ./dist
        mkdir ./dist/ESP_Packages
        cp ./ESP_Packages/README.md ./dist/ESP_Packages
    - name: Create macOs Artefact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: espeasyflasher_macOs
        # A file, directory or wildcard pattern that describes what to upload
        path: ./dist
        # The desired behavior if no files are found using the provided path.
