name: main_ci_cd
#on: [push]
on:
  push:
    branches:
      - '**'

jobs:
  test:
    uses: ./.github/workflows/test.yml
  build-targets:
    needs: test
    uses: ./.github/workflows/build_targets.yml
    with:
      target: 'all'