name: main_ci_cd

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python "3.10"
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyserial
        pip install esptool
        pip install pylint
    - name: Analysing code with pylint
      run: |        
        pylint --rcfile=./Scripts/pylint.rc espeasyflasher.py
        pylint --rcfile=./Scripts/pylint.rc ./eef_modules
        pylint --rcfile=./Scripts/pylint.rc ./tests
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python "3.10"
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install esptool
    - name: Testing EspEasyFlasher_2.0
      run: pytest tests
  windows_exe:
    runs-on: windows-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [pylint, pytest]
    - uses: actions/checkout@v3
    - name: Set up Python "3.10"
    - uses: actions/setup-python@v3
      with: 
        python-version: "3.10"
    - run: python --version