name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # for the beginning check only python 3.10
        # python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyserial
        pip install esptool
        pip install pylint
    - name: Analysing code with pylint
      run: |        
        pylint --rcfile=./Scripts/pylint.rc espeasyflasher.py
        pylint --rcfile=./Scripts/pylint.rc ./eef_modules
        pylint --rcfile=./Scripts/pylint.rc ./tests