name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # for the beginning check only python 3.10
        # python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyserial
        pip install esptool
        pip install pylint
    - name: Analysing espeasyflasher.py with pylint
      run: pylint espeasyflasher.py
    - name: Analysing eef sub modules with pylint
      run: |
        cd eef_modules
        pylint `ls -R|grep .py$|xargs`