on:
    workflow_call:
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python "3.12"
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyserial
        pip install esptool
        pip install setuptools
        pip install pylint
    - name: Analysing code with pylint
      run: |        
        pylint --rcfile=./Scripts/pylint.rc espeasyflasher.py
        pylint --rcfile=./Scripts/pylint.rc ./eef_modules
        pylint --rcfile=./Scripts/pylint.rc ./tests
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python "3.12"
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyserial
        pip install pytest
        pip install esptool
        pip install setuptools
    - name: Testing EspEasyFlasher_2.0
      run: pytest tests